# Generated by Django 3.1.5 on 2021-01-10 13:02

import django.core.validators
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Normalised field to keep track of the current quantity in stock'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='declared_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.UUIDField(unique=True),
        ),
    ]
