# Generated by Django 3.1.5 on 2021-01-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210110_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='current_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Normalised field to keep track of the current quantity in stock'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration_date',
            field=models.DateField(db_index=True),
        ),
    ]
